# LINE SETTINGS
LINE_SHAPE = "square"
LINE_RESIZEMODE = "user"
LINE_COLOUR = "white"
NUM_MIDDLE_LINES = 45
MIDDLE_LINE_HEIGHT = 10
MIDDLE_LINE_WIDTH = 0.1

# SCREEN SETTINGS
SCREEN_WIDTH = 900
SCREEN_HEIGHT = NUM_MIDDLE_LINES * MIDDLE_LINE_HEIGHT
SCREEN_BG_COLOUR = "black"
OFFSET = 40

# PADDLE SETTINGS
PADDLE_WIDTH_PX = 20
PADDLE_WIDTH = .5
PADDLE_HEIGHT = 3
PADDLE_LOCATIONS_X_AXIS = [-(SCREEN_WIDTH-OFFSET) // 2 , (SCREEN_WIDTH-OFFSET-(PADDLE_WIDTH_PX * PADDLE_WIDTH)) // 2]
MOVE_CHUNK = 10

# SCREEN LAYOUT SETTINGS
