# SCREEN SETTINGS
BG_COLOUR = "orange"
GAME_SCREEN = 600
GAME_TITLE = "Snake Game"
TRACER_OFF = 0


# SINGLE PLAYER SETTINGS
SINGLEPLAYER_SNAKE_COLOUR = "black"
SINGLEPLAYER_SNAKE_LOCATION = {"x": -280, "y": 0}
SINGLEPLAYER_SCORE_LOCATION = {"x": 0, "y": 280}

# SNAKE SETTINGS
SNAKE_COLOURS = ["white", "black"]
SNAKE_LOCATIONS = [{"x": -280, "y": 200}, {"x": -280, "y": -200}]

# SCORE SETTINGS
SCORE_LOCATIONS = [{"x": -240, "y": 280}, {"x": 240, "y": 280}]

# TIME SETTINGS
MAX_TIME = 100     # 5 minutes
TIME_LOCATION = {"x": 0, "y": 280}

# FOOD SETTINGS
FOOD_SPAWNRATE = 15
FOOD_SHAPE_MULTIPLIER = 0.5
MARGIN = 10
SQUARE_SIZE = 20
FOOD_COLOUR = "#ffff00"

# GENERAL SNAKE SETTINGS
SHAPESIZE = 1
MOVE_DISTANCE = 20
RIGHT = 0
UP = 90
LEFT = 180
DOWN = 270

# SNAKE SETTINGS
SNAKE_LENGTH = 5
SNAKE_SPEED = .03

# TEXT/SCORE SETTINGS
ALIGNMENT = "center"
SCORE_FONT = ("Arial", 12, "bold")
SET_MOVE_FALSE = False
GAME_OVER_FONT = ("Arial", 15, "bold")
SCORE_POS = {"x":0, "y": 275}

# TEXT OBJECT SETTINGS
GAME_OVER = "GAME OVER"
RESTART = "Press R to restart or Q to quit"
RESTART_TEXT_LOCATION = {"x":0, "y": -30}
START_TEXT = "PRESS ANY BUTTON TO START THE GAME"
TEXT_FLASH = .45

# 'Menu' Text
ONE_TWO_PLAYER_TEXT = "PRESS 1 FOR SINGLE PLAYER, PRESS 2 FOR MULTI PLAYER"
ONE_TWO_PLAYER_TEXT_LOCATION = {"x":0, "y": -40}

